<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>VECTORES AUTOREGRESIVOS (VAR)</title>
  <meta name="description" content="VECTORES AUTOREGRESIVOS (VAR)" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="VECTORES AUTOREGRESIVOS (VAR)" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="VECTORES AUTOREGRESIVOS (VAR)" />
  
  
  

<meta name="author" content="Luis Ortiz-Cevallos" />


<meta name="date" content="2022-03-15" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  


<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />










<script>
/* ========================================================================
 * Bootstrap: transition.js v3.3.7
 * http://getbootstrap.com/javascript/#transitions
 * ========================================================================
 * Copyright 2011-2016 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 * ======================================================================== */


+function ($) {
  'use strict';

  // CSS TRANSITION SUPPORT (Shoutout: http://www.modernizr.com/)
  // ============================================================

  function transitionEnd() {
    var el = document.createElement('bootstrap')

    var transEndEventNames = {
      WebkitTransition : 'webkitTransitionEnd',
      MozTransition    : 'transitionend',
      OTransition      : 'oTransitionEnd otransitionend',
      transition       : 'transitionend'
    }

    for (var name in transEndEventNames) {
      if (el.style[name] !== undefined) {
        return { end: transEndEventNames[name] }
      }
    }

    return false // explicit for ie8 (  ._.)
  }

  // http://blog.alexmaccaw.com/css-transitions
  $.fn.emulateTransitionEnd = function (duration) {
    var called = false
    var $el = this
    $(this).one('bsTransitionEnd', function () { called = true })
    var callback = function () { if (!called) $($el).trigger($.support.transition.end) }
    setTimeout(callback, duration)
    return this
  }

  $(function () {
    $.support.transition = transitionEnd()

    if (!$.support.transition) return

    $.event.special.bsTransitionEnd = {
      bindType: $.support.transition.end,
      delegateType: $.support.transition.end,
      handle: function (e) {
        if ($(e.target).is(this)) return e.handleObj.handler.apply(this, arguments)
      }
    }
  })

}(jQuery);
</script>
<script>
/* ========================================================================
 * Bootstrap: collapse.js v3.3.7
 * http://getbootstrap.com/javascript/#collapse
 * ========================================================================
 * Copyright 2011-2016 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 * ======================================================================== */

/* jshint latedef: false */

+function ($) {
  'use strict';

  // COLLAPSE PUBLIC CLASS DEFINITION
  // ================================

  var Collapse = function (element, options) {
    this.$element      = $(element)
    this.options       = $.extend({}, Collapse.DEFAULTS, options)
    this.$trigger      = $('[data-toggle="collapse"][href="#' + element.id + '"],' +
                           '[data-toggle="collapse"][data-target="#' + element.id + '"]')
    this.transitioning = null

    if (this.options.parent) {
      this.$parent = this.getParent()
    } else {
      this.addAriaAndCollapsedClass(this.$element, this.$trigger)
    }

    if (this.options.toggle) this.toggle()
  }

  Collapse.VERSION  = '3.3.7'

  Collapse.TRANSITION_DURATION = 350

  Collapse.DEFAULTS = {
    toggle: true
  }

  Collapse.prototype.dimension = function () {
    var hasWidth = this.$element.hasClass('width')
    return hasWidth ? 'width' : 'height'
  }

  Collapse.prototype.show = function () {
    if (this.transitioning || this.$element.hasClass('in')) return

    var activesData
    var actives = this.$parent && this.$parent.children('.panel').children('.in, .collapsing')

    if (actives && actives.length) {
      activesData = actives.data('bs.collapse')
      if (activesData && activesData.transitioning) return
    }

    var startEvent = $.Event('show.bs.collapse')
    this.$element.trigger(startEvent)
    if (startEvent.isDefaultPrevented()) return

    if (actives && actives.length) {
      Plugin.call(actives, 'hide')
      activesData || actives.data('bs.collapse', null)
    }

    var dimension = this.dimension()

    this.$element
      .removeClass('collapse')
      .addClass('collapsing')[dimension](0)
      .attr('aria-expanded', true)

    this.$trigger
      .removeClass('collapsed')
      .attr('aria-expanded', true)

    this.transitioning = 1

    var complete = function () {
      this.$element
        .removeClass('collapsing')
        .addClass('collapse in')[dimension]('')
      this.transitioning = 0
      this.$element
        .trigger('shown.bs.collapse')
    }

    if (!$.support.transition) return complete.call(this)

    var scrollSize = $.camelCase(['scroll', dimension].join('-'))

    this.$element
      .one('bsTransitionEnd', $.proxy(complete, this))
      .emulateTransitionEnd(Collapse.TRANSITION_DURATION)[dimension](this.$element[0][scrollSize])
  }

  Collapse.prototype.hide = function () {
    if (this.transitioning || !this.$element.hasClass('in')) return

    var startEvent = $.Event('hide.bs.collapse')
    this.$element.trigger(startEvent)
    if (startEvent.isDefaultPrevented()) return

    var dimension = this.dimension()

    this.$element[dimension](this.$element[dimension]())[0].offsetHeight

    this.$element
      .addClass('collapsing')
      .removeClass('collapse in')
      .attr('aria-expanded', false)

    this.$trigger
      .addClass('collapsed')
      .attr('aria-expanded', false)

    this.transitioning = 1

    var complete = function () {
      this.transitioning = 0
      this.$element
        .removeClass('collapsing')
        .addClass('collapse')
        .trigger('hidden.bs.collapse')
    }

    if (!$.support.transition) return complete.call(this)

    this.$element
      [dimension](0)
      .one('bsTransitionEnd', $.proxy(complete, this))
      .emulateTransitionEnd(Collapse.TRANSITION_DURATION)
  }

  Collapse.prototype.toggle = function () {
    this[this.$element.hasClass('in') ? 'hide' : 'show']()
  }

  Collapse.prototype.getParent = function () {
    return $(this.options.parent)
      .find('[data-toggle="collapse"][data-parent="' + this.options.parent + '"]')
      .each($.proxy(function (i, element) {
        var $element = $(element)
        this.addAriaAndCollapsedClass(getTargetFromTrigger($element), $element)
      }, this))
      .end()
  }

  Collapse.prototype.addAriaAndCollapsedClass = function ($element, $trigger) {
    var isOpen = $element.hasClass('in')

    $element.attr('aria-expanded', isOpen)
    $trigger
      .toggleClass('collapsed', !isOpen)
      .attr('aria-expanded', isOpen)
  }

  function getTargetFromTrigger($trigger) {
    var href
    var target = $trigger.attr('data-target')
      || (href = $trigger.attr('href')) && href.replace(/.*(?=#[^\s]+$)/, '') // strip for ie7

    return $(target)
  }


  // COLLAPSE PLUGIN DEFINITION
  // ==========================

  function Plugin(option) {
    return this.each(function () {
      var $this   = $(this)
      var data    = $this.data('bs.collapse')
      var options = $.extend({}, Collapse.DEFAULTS, $this.data(), typeof option == 'object' && option)

      if (!data && options.toggle && /show|hide/.test(option)) options.toggle = false
      if (!data) $this.data('bs.collapse', (data = new Collapse(this, options)))
      if (typeof option == 'string') data[option]()
    })
  }

  var old = $.fn.collapse

  $.fn.collapse             = Plugin
  $.fn.collapse.Constructor = Collapse


  // COLLAPSE NO CONFLICT
  // ====================

  $.fn.collapse.noConflict = function () {
    $.fn.collapse = old
    return this
  }


  // COLLAPSE DATA-API
  // =================

  $(document).on('click.bs.collapse.data-api', '[data-toggle="collapse"]', function (e) {
    var $this   = $(this)

    if (!$this.attr('data-target')) e.preventDefault()

    var $target = getTargetFromTrigger($this)
    var data    = $target.data('bs.collapse')
    var option  = data ? 'toggle' : $this.data()

    Plugin.call($target, option)
  })

}(jQuery);
</script>
<script>
window.initializeCodeFolding = function(show) {

  // handlers for show-all and hide all
  $("#rmd-show-all-code").click(function() {
    // close the dropdown menu when an option is clicked
    $("#allCodeButton").dropdown("toggle");
    $('div.r-code-collapse').each(function() {
      $(this).collapse('show');
    });
  });
  $("#rmd-hide-all-code").click(function() {
    // close the dropdown menu when an option is clicked
    $("#allCodeButton").dropdown("toggle");
    $('div.r-code-collapse').each(function() {
      $(this).collapse('hide');
    });
  });

  // index for unique code element ids
  var currentIndex = 1;

  // select all R code blocks
  var rCodeBlocks = $('pre.sourceCode, pre.r, pre.python, pre.bash, pre.sql, pre.cpp, pre.stan');
  rCodeBlocks.each(function() {

    // if code block has been labeled with class `fold-show`, show the code on init!
    var classList = $(this).attr('class').split(/\s+/);
    for (var i = 0; i < classList.length; i++) {
    if (classList[i] === 'fold-show') {
        show = true;
      }
    }

    // create a collapsable div to wrap the code in
    var div = $('<div class="collapse r-code-collapse"></div>');
    if (show)
      div.addClass('in');
    var id = 'rcode-643E0F36' + currentIndex++;
    div.attr('id', id);
    $(this).before(div);
    $(this).detach().appendTo(div);

    // add a show code button right above
    var showCodeText = $('<span>' + (show ? 'Hide' : 'Code') + '</span>');
    var showCodeButton = $('<button type="button" class="btn btn-default btn-xs code-folding-btn pull-right"></button>');
    showCodeButton.append(showCodeText);
    showCodeButton
        .attr('data-toggle', 'collapse')
        .attr('data-target', '#' + id)
        .attr('aria-expanded', show)
        .attr('aria-controls', id);

    var buttonRow = $('<div class="row"></div>');
    var buttonCol = $('<div class="col-md-12"></div>');

    buttonCol.append(showCodeButton);
    buttonRow.append(buttonCol);

    div.before(buttonRow);

    // hack: return show to false, otherwise all next codeBlocks will be shown!
    show = false;

    // update state of button on show/hide
    div.on('hidden.bs.collapse', function () {
      showCodeText.text('Code');
    });
    div.on('show.bs.collapse', function () {
      showCodeText.text('Hide');
    });
  });

}
</script>
<script>
/* ========================================================================
 * Bootstrap: dropdown.js v3.3.7
 * http://getbootstrap.com/javascript/#dropdowns
 * ========================================================================
 * Copyright 2011-2016 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 * ======================================================================== */


+function ($) {
  'use strict';

  // DROPDOWN CLASS DEFINITION
  // =========================

  var backdrop = '.dropdown-backdrop'
  var toggle   = '[data-toggle="dropdown"]'
  var Dropdown = function (element) {
    $(element).on('click.bs.dropdown', this.toggle)
  }

  Dropdown.VERSION = '3.3.7'

  function getParent($this) {
    var selector = $this.attr('data-target')

    if (!selector) {
      selector = $this.attr('href')
      selector = selector && /#[A-Za-z]/.test(selector) && selector.replace(/.*(?=#[^\s]*$)/, '') // strip for ie7
    }

    var $parent = selector && $(selector)

    return $parent && $parent.length ? $parent : $this.parent()
  }

  function clearMenus(e) {
    if (e && e.which === 3) return
    $(backdrop).remove()
    $(toggle).each(function () {
      var $this         = $(this)
      var $parent       = getParent($this)
      var relatedTarget = { relatedTarget: this }

      if (!$parent.hasClass('open')) return

      if (e && e.type == 'click' && /input|textarea/i.test(e.target.tagName) && $.contains($parent[0], e.target)) return

      $parent.trigger(e = $.Event('hide.bs.dropdown', relatedTarget))

      if (e.isDefaultPrevented()) return

      $this.attr('aria-expanded', 'false')
      $parent.removeClass('open').trigger($.Event('hidden.bs.dropdown', relatedTarget))
    })
  }

  Dropdown.prototype.toggle = function (e) {
    var $this = $(this)

    if ($this.is('.disabled, :disabled')) return

    var $parent  = getParent($this)
    var isActive = $parent.hasClass('open')

    clearMenus()

    if (!isActive) {
      if ('ontouchstart' in document.documentElement && !$parent.closest('.navbar-nav').length) {
        // if mobile we use a backdrop because click events don't delegate
        $(document.createElement('div'))
          .addClass('dropdown-backdrop')
          .insertAfter($(this))
          .on('click', clearMenus)
      }

      var relatedTarget = { relatedTarget: this }
      $parent.trigger(e = $.Event('show.bs.dropdown', relatedTarget))

      if (e.isDefaultPrevented()) return

      $this
        .trigger('focus')
        .attr('aria-expanded', 'true')

      $parent
        .toggleClass('open')
        .trigger($.Event('shown.bs.dropdown', relatedTarget))
    }

    return false
  }

  Dropdown.prototype.keydown = function (e) {
    if (!/(38|40|27|32)/.test(e.which) || /input|textarea/i.test(e.target.tagName)) return

    var $this = $(this)

    e.preventDefault()
    e.stopPropagation()

    if ($this.is('.disabled, :disabled')) return

    var $parent  = getParent($this)
    var isActive = $parent.hasClass('open')

    if (!isActive && e.which != 27 || isActive && e.which == 27) {
      if (e.which == 27) $parent.find(toggle).trigger('focus')
      return $this.trigger('click')
    }

    var desc = ' li:not(.disabled):visible a'
    var $items = $parent.find('.dropdown-menu' + desc)

    if (!$items.length) return

    var index = $items.index(e.target)

    if (e.which == 38 && index > 0)                 index--         // up
    if (e.which == 40 && index < $items.length - 1) index++         // down
    if (!~index)                                    index = 0

    $items.eq(index).trigger('focus')
  }


  // DROPDOWN PLUGIN DEFINITION
  // ==========================

  function Plugin(option) {
    return this.each(function () {
      var $this = $(this)
      var data  = $this.data('bs.dropdown')

      if (!data) $this.data('bs.dropdown', (data = new Dropdown(this)))
      if (typeof option == 'string') data[option].call($this)
    })
  }

  var old = $.fn.dropdown

  $.fn.dropdown             = Plugin
  $.fn.dropdown.Constructor = Dropdown


  // DROPDOWN NO CONFLICT
  // ====================

  $.fn.dropdown.noConflict = function () {
    $.fn.dropdown = old
    return this
  }


  // APPLY TO STANDARD DROPDOWN ELEMENTS
  // ===================================

  $(document)
    .on('click.bs.dropdown.data-api', clearMenus)
    .on('click.bs.dropdown.data-api', '.dropdown form', function (e) { e.stopPropagation() })
    .on('click.bs.dropdown.data-api', toggle, Dropdown.prototype.toggle)
    .on('keydown.bs.dropdown.data-api', toggle, Dropdown.prototype.keydown)
    .on('keydown.bs.dropdown.data-api', '.dropdown-menu', Dropdown.prototype.keydown)

}(jQuery);
</script>
<style type="text/css">
.code-folding-btn {
  margin-bottom: 4px;
}

.row { display: flex; }
.collapse { display: none; }
.in { display:block }
.pull-right > .dropdown-menu {
    right: 0;
    left: auto;
}

.dropdown-menu {
    position: absolute;
    top: 100%;
    left: 0;
    z-index: 1000;
    display: none;
    float: left;
    min-width: 160px;
    padding: 5px 0;
    margin: 2px 0 0;
    font-size: 14px;
    text-align: left;
    list-style: none;
    background-color: #fff;
    -webkit-background-clip: padding-box;
    background-clip: padding-box;
    border: 1px solid #ccc;
    border: 1px solid rgba(0,0,0,.15);
    border-radius: 4px;
    -webkit-box-shadow: 0 6px 12px rgba(0,0,0,.175);
    box-shadow: 0 6px 12px rgba(0,0,0,.175);
}

.open > .dropdown-menu {
    display: block;
    color: #ffffff;
    background-color: #ffffff;
    background-image: none;
    border-color: #92897e;
}

.dropdown-menu > li > a {
  display: block;
  padding: 3px 20px;
  clear: both;
  font-weight: 400;
  line-height: 1.42857143;
  color: #000000;
  white-space: nowrap;
}

.dropdown-menu > li > a:hover,
.dropdown-menu > li > a:focus {
  color: #ffffff;
  text-decoration: none;
  background-color: #e95420;
}

.dropdown-menu > .active > a,
.dropdown-menu > .active > a:hover,
.dropdown-menu > .active > a:focus {
  color: #ffffff;
  text-decoration: none;
  background-color: #e95420;
  outline: 0;
}
.dropdown-menu > .disabled > a,
.dropdown-menu > .disabled > a:hover,
.dropdown-menu > .disabled > a:focus {
  color: #aea79f;
}

.dropdown-menu > .disabled > a:hover,
.dropdown-menu > .disabled > a:focus {
  text-decoration: none;
  cursor: not-allowed;
  background-color: transparent;
  background-image: none;
  filter: progid:DXImageTransform.Microsoft.gradient(enabled = false);
}

.btn {
  display: inline-block;
  margin-bottom: 1;
  font-weight: normal;
  text-align: center;
  white-space: nowrap;
  vertical-align: middle;
  -ms-touch-action: manipulation;
      touch-action: manipulation;
  cursor: pointer;
  background-image: none;
  border: 1px solid transparent;
  padding: 4px 8px;
  font-size: 14px;
  line-height: 1.42857143;
  border-radius: 4px;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}

.btn:focus,
.btn:active:focus,
.btn.active:focus,
.btn.focus,
.btn:active.focus,
.btn.active.focus {
  outline: 5px auto -webkit-focus-ring-color;
  outline-offset: -2px;
}
.btn:hover,
.btn:focus,
.btn.focus {
  color: #ffffff;
  text-decoration: none;
}
.btn:active,
.btn.active {
  background-image: none;
  outline: 0;
  box-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);
}
.btn.disabled,
.btn[disabled],
fieldset[disabled] .btn {
  cursor: not-allowed;
  filter: alpha(opacity=65);
  opacity: 0.65;
  box-shadow: none;
}
a.btn.disabled,
fieldset[disabled] a.btn {
  pointer-events: none;
}
.btn-default {
  color: #ffffff;
  background-color: #aea79f; #important
  border-color: #aea79f;
}

.btn-default:focus,
.btn-default.focus {
  color: #ffffff;
  background-color: #978e83;
  border-color: #6f675e;
}

.btn-default:hover {
  color: #ffffff;
  background-color: #978e83;
  border-color: #92897e;
}
.btn-default:active,
.btn-default.active,
.btn-group > .btn:not(:first-child):not(:last-child):not(.dropdown-toggle) {
  border-radius: 0;
}
.btn-group > .btn:first-child {
  margin-left: 0;
}
.btn-group > .btn:first-child:not(:last-child):not(.dropdown-toggle) {
  border-top-right-radius: 0;
  border-bottom-right-radius: 0;
}
.btn-group > .btn:last-child:not(:first-child),
.btn-group > .dropdown-toggle:not(:first-child) {
  border-top-left-radius: 0;
  border-bottom-left-radius: 0;
}
.btn-group > .btn-group {
  float: left;
}
.btn-group > .btn-group:not(:first-child):not(:last-child) > .btn {
  border-radius: 0;
}
.btn-group > .btn-group:first-child:not(:last-child) > .btn:last-child,
.btn-group > .btn-group:first-child:not(:last-child) > .dropdown-toggle {
  border-top-right-radius: 0;
  border-bottom-right-radius: 0;
}
.btn-group > .btn-group:last-child:not(:first-child) > .btn:first-child {
  border-top-left-radius: 0;
  border-bottom-left-radius: 0;
}
.btn-group .dropdown-toggle:active,
.btn-group.open .dropdown-toggle {
  outline: 0;
}
.btn-group > .btn + .dropdown-toggle {
  padding-right: 8px;
  padding-left: 8px;
}
.btn-group > .btn-lg + .dropdown-toggle {
  padding-right: 12px;
  padding-left: 12px;
}
.btn-group.open .dropdown-toggle {
  box-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);
}
.btn-group.open .dropdown-toggle.btn-link {
  box-shadow: none;
}

</style>
<script>
var str = '<div class="btn-group pull-right" style="position: fixed; right: 50px; top: 10px; z-index: 200"><button type="button" class="btn btn-default btn-xs dropdown-toggle" id="allCodeButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" data-_extension-text-contrast=""><span>Code</span> <span class="caret"></span></button><ul class="dropdown-menu" style="min-width: 50px;"><li><a id="rmd-show-all-code" href="#">Show All Code</a></li><li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li></ul></div>';
document.write(str);
</script>
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "hide");
});
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path=""><a href="#introducción"><i class="fa fa-check"></i><b>1</b> INTRODUCCIÓN</a>
<ul>
<li class="chapter" data-level="1.1" data-path=""><a href="#el-modelo-de-vectores-autoregresivos-var"><i class="fa fa-check"></i><b>1.1</b> El modelo de vectores autoregresivos (VAR)</a></li>
<li class="chapter" data-level="1.2" data-path=""><a href="#función-impulso-respuesta"><i class="fa fa-check"></i><b>1.2</b> Función Impulso Respuesta</a></li>
<li class="chapter" data-level="1.3" data-path=""><a href="#vectores-autoregresivos-estructurales"><i class="fa fa-check"></i><b>1.3</b> Vectores autoregresivos estructurales</a></li>
<li class="chapter" data-level="1.4" data-path=""><a href="#ortogonalización"><i class="fa fa-check"></i><b>1.4</b> Ortogonalización</a></li>
<li class="chapter" data-level="1.5" data-path=""><a href="#supuestos-de-ortogonalización"><i class="fa fa-check"></i><b>1.5</b> Supuestos de Ortogonalización</a></li>
<li class="chapter" data-level="1.6" data-path=""><a href="#ortogonalización-de-sims"><i class="fa fa-check"></i><b>1.6</b> Ortogonalización de Sims</a></li>
<li class="chapter" data-level="1.7" data-path=""><a href="#paquete-en-r"><i class="fa fa-check"></i><b>1.7</b> Paquete en R</a></li>
<li class="chapter" data-level="1.8" data-path=""><a href="#bla-bla"><i class="fa fa-check"></i><b>1.8</b> BLA Bla</a></li>
</ul></li>
<li class="chapter" data-level="" data-path=""><a href="#referencias"><i class="fa fa-check"></i>Referencias</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">VECTORES AUTOREGRESIVOS (VAR)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="header">
<h1 class="title">VECTORES AUTOREGRESIVOS (VAR)</h1>
<p class="author"><em><a href="https://ortiz-cevallos.github.io/MYSELF/">Luis Ortiz-Cevallos</a></em></p>
<p class="date"><em>2022-03-15</em></p>
</div>
<div id="introducción" class="section level1" number="1">
<h1><span class="header-section-number">Capítulo 1</span> INTRODUCCIÓN</h1>
<div id="el-modelo-de-vectores-autoregresivos-var" class="section level2" number="1.1">
<h2><span class="header-section-number">1.1</span> El modelo de vectores autoregresivos (VAR)</h2>
<p>Un VAR consiste en un conjunto de k variables endógenas <span class="math inline">\(Y_{t}=\{y_{1t},\cdots, y_{kt}\}\)</span>.</p>
<p>En el caso de un proceso ARMA(2,1):
<span class="math inline">\(Y_t = \Phi_1Y_{t-1} + \Phi_2Y_{t-2} + u_t + \theta_1u_{t-1}\)</span></p>
<p>Podemos reescribirlo como:
<span class="math display">\[\begin{equation}
\left( \begin{array}{c}
Y_{t} \\
Y_{t-1} \\
u_{t} 
\end{array}
\right)=\left( \begin{array}{ccc}
\Phi_1 &amp; \Phi_2 &amp; \theta_1\\
1 &amp; 0 &amp; 0\\
0 &amp; 0 &amp; 0
\end{array}
\right) \left( \begin{array}{c}
Y_{t-1} \\
Y_{t-2} \\
u_{t-1} 
\end{array}
\right)+\left( \begin{array}{c}
1\\
0 \\
1
\end{array}
\right) \left( \begin{array}{c}
u_{t} \\
0 \\
0
\end{array}
\right) 
\nonumber
\end{equation}\]</span></p>
<p>Lo anterior no es otra cosa que un proceso AR(1), matricialmente:</p>
<p><span class="math inline">\(x_t = Ax_{t−1} + Cw_t\)</span></p>
<p>Este proceso tiene los siguientes supuestos:</p>
<ol style="list-style-type: decimal">
<li><p><span class="math inline">\(E(w_{t})=0\)</span></p></li>
<li><p><span class="math inline">\(E(w_{t}w_{t}^{\tau})=\Sigma_{w}\)</span> una matriz de covarianza invariante en el tiempo la cual es definida positiva.</p></li>
</ol>
</div>
<div id="función-impulso-respuesta" class="section level2" number="1.2">
<h2><span class="header-section-number">1.2</span> Función Impulso Respuesta</h2>
<p>La función impulso respuesta es la senda que sigue una serie cuando enfrenta un shock unitario.</p>
<p>Es interesante por:</p>
<ol style="list-style-type: decimal">
<li>Caracteriza el comportamiento del modelo.</li>
<li>Permite la discusión de quién causa a quién.</li>
</ol>
<p>Para una proceso AR(1) <span class="math inline">\(y_{t}=\phi y_{t-1}+\epsilon_{t}\)</span> el cual lo expresamos en MA(<span class="math inline">\(\infty\)</span>) como <span class="math inline">\(y_{t}=\sum_{j=0}^{\infty}\phi^{j} \epsilon_{t-j}\)</span>, su impulso respuesta es:</p>
<p><span class="math inline">\(\begin{array}{cccccccc} \epsilon_{t} &amp;\colon &amp;0&amp;0&amp;1&amp;0&amp;0&amp;0 \\ x_{t} &amp;\colon &amp;0&amp;0&amp;\phi&amp;\phi^{2}&amp;\phi^{3}&amp;\cdots \end{array}\)</span></p>
<p>¿Por qué es importante definir un proceso como un MA<span class="math inline">\((\infty)\)</span>?</p>
<ol style="list-style-type: decimal">
<li>La representación MA infinito de todo proceso es <em>la función impulso respuesta</em></li>
<li>La función impulso respuesta es equivalente a <span class="math inline">\(E_{t}(x_{t+h})-E_{t-1}(x_{t+h})\)</span> que no es otra cosa que el error de pronóstico hacia h pasos adelante.</li>
</ol>
<p>Noten que los pronósticos para horizontes <span class="math inline">\(h\geq1\)</span> de un proceso VAR(p) puede ser generado de manera recursiva.
<span class="math inline">\(x_{t+h/t} = A_{1}x_{t+h-1/t} + \cdots+A_{p}x_{t+h-p/t}\)</span></p>
</div>
<div id="vectores-autoregresivos-estructurales" class="section level2" number="1.3">
<h2><span class="header-section-number">1.3</span> Vectores autoregresivos estructurales</h2>
<p>Casi todas las variables en economía podrían considerarse
hasta cierto punto endógenas. Sin embargo, prima un criterio de relevancia. Si bien es cierto que un comerciante al fijar el precio de una manzana está afectando la inflación, parece razonable suponer que la inflación es exógena al precio de las manzanas de este comerciante.</p>
<p>Por tanto si la inflación está dado por <span class="math inline">\(\pi\)</span> y el precio de las manzanas por <span class="math inline">\(m\)</span> tenemos el siguiente VAR</p>
<p><span class="math display">\[\begin{align}
\alpha_{1,1}^{+}\pi_t+\alpha_{1,2}^{+}m_t &amp;= \beta_{1,1}^{+}\pi_{t-1}+\beta_{1,2}^{+}m_{t-1}+e_{\pi,t}\\
\alpha_{2,1}^{+}\pi_t+\alpha_{2,2}^{+}m_t &amp;= \beta_{2,1}^{+}\pi_{t-1}+\beta_{2,2}^{+}m_{t-1}+e_{m,t}
\end{align}\]</span></p>
<p>Sí normalizamos el VAR tenemos lo siguiente:
<span class="math display">\[\begin{align}
\pi_t+\alpha_{1,2}m_t &amp;= \beta_{1,1}\pi_{t-1}+\beta_{1,2}m_{t-1}+e_{\pi,t}\\
\alpha_{2,1}\pi_t+m_t &amp;= \beta_{2,1}\pi_{t-1}+\beta_{2,2}m_{t-1}+e_{m,t}
\end{align}\]</span></p>
<p>Si resolvemos el sistema de ecuaciones simultáneas, despejamos las
variables obtenemos un VAR en su forma reducida; comenzamos con la primera ecuación:</p>
<p><span class="math display">\[\begin{align}
\pi_{t} &amp;=\beta_{1,1}\pi_{t-1}+\beta_{1,2}m_{t-1}+e_{\pi,t}\\
        &amp;- \alpha_{1,2}(\beta_{2,1}\pi_{t-1}+\beta_{2,2}m_{t-1}-\alpha_{2,1}\pi_t+e_{m,t})\\
        \pi_{t} &amp;=\frac{(\beta_{1,1}-\alpha_{1,2}\beta_{2,1})}{(1+\alpha_{1,2}\alpha_{2,1})}\pi_{t-1}+ \frac{(\beta_{1,2}-\alpha_{1,2}\beta_{2,2})}{(1+\alpha_{1,2}\alpha_{2,1})}m_{t-1}+\frac{1}{(1+\alpha_{1,2}\alpha_{2,1})}e_{\pi,t}- \frac{\alpha_{1,2}}{(1+\alpha_{1,2}\alpha_{2,1})}e_{m,t}\\
 \pi_{t}&amp;=\gamma_{\pi}\pi_{t-1}+\gamma_{m}m_{t-1}+\gamma_{e_{\pi}}e_{\pi,t}+\gamma_{e_{m}}e_{m,t}       
\end{align}\]</span></p>
<p>De manera análoga para las manzanas:
<span class="math display">\[\begin{align}
m_{t} &amp;=\beta_{2,1}\pi_{t-1}+\beta_{2,2}m_{t-1}+e_{m,t}\\
        &amp;- \alpha_{2,1}(\beta_{1,1}\pi_{t-1}+\beta_{1,2}m_{t-1}-\alpha_{1,2}m_t+e_{\pi,t})\\
        m_{t} &amp;=\frac{(\beta_{2,1}-\alpha_{2,1}\beta_{1,1})}{(1+\alpha_{1,2}\alpha_{2,1})}\pi_{t-1}+ \frac{(\beta_{2,2}-\alpha_{2,1}\beta_{1,2})}{(1+\alpha_{1,2}\alpha_{2,1})}m_{t-1}+\frac{\alpha_{2,1}}{(1+\alpha_{1,2}\alpha_{2,1})}e_{\pi,t}- \frac{1}{(1+\alpha_{1,2}\alpha_{2,1})}e_{m,t}\\
 m_{t}&amp;=\omega_{\pi}\pi_{t-1}+\omega_{m}m_{t-1}+\omega_{e_{\pi}}e_{\pi,t}+\omega_{e_{m}}e_{m,t}       
\end{align}\]</span></p>
<p>Entonces ahora tenemos el siguiente sistema:
<span class="math display">\[\begin{align}
\pi_{t}&amp;=\gamma_{\pi}\pi_{t-1}+\gamma_{m}m_{t-1}+\gamma_{e_{\pi}}e_{\pi,t}+\gamma_{e_{m}}e_{m,t}\\   
 m_{t}&amp;=\omega_{\pi}\pi_{t-1}+\omega_{m}m_{t-1}+\omega_{e_{\pi}}e_{\pi,t}+\omega_{e_{m}}e_{m,t}       
\end{align}\]</span></p>
<p>El sistema anterior puede escribirse de forma matricial como:
<span class="math display">\[\begin{equation}
    \left( \begin{array}{c}
    \pi_{t} \\
      m_{t} 
    \end{array}\right)=\left( \begin{array}{cc}
 \gamma_{\pi} &amp; \gamma_{m}\\
 \omega_{\pi} &amp; \omega_{m}
    \end{array}
    \right) \left( \begin{array}{c}
    \pi_{t-1}\\
      m_{t-1}
    \end{array}
    \right) +
\left( \begin{array}{cc}
 \gamma_{e_{\pi}} &amp; \gamma_{e_{m}}\\
 \omega_{e_{\pi}} &amp; \omega_{e_{m}}
    \end{array}
    \right) \left( \begin{array}{c}
    e_{\pi,t}\\
    e_{m,t} 
    \end{array}
    \right) 
\end{equation}\]</span></p>
<p>Expresándolo de forma matricial tenermos:</p>
<p><span class="math display">\[\begin{equation}
\label{e1}
x_t = \Gamma x_{t−1} + Zw_t
\end{equation}\]</span></p>
<p>La ecuación anterior es la <em>forma estructural</em>. Sin embargo, cuando se estima el VAR se hace en su <em>forma reducida</em>, la que resulta trás premultiplicar por la matriz A:
<span class="math display">\[\begin{equation}
\label{e2}
Ax_t = A\Gamma x_{t−1} + Bw_t
\end{equation}\]</span></p>
<p>Si asumimos que los <em>errores estructurales</em> que integran el vector <span class="math inline">\(w_{t}\)</span> son ruido blanco, y que los coeficientes en la matriz <span class="math inline">\(\Gamma\)</span> son <em>estructurales</em> los cuales difieran de sus contrapartes en su forma reducida.</p>
<p>Para ver lo anterior, multiplicamos la ecuación anterior por <span class="math inline">\(A^{-1}\)</span>:</p>
<p><span class="math display">\[\begin{align}
x_t &amp;= A^{-1}A\Gamma x_{t−1} + A^{-1}Bw_t\\
x_t &amp;= \Gamma x_{t−1} + \eta_t
\end{align}\]</span></p>
<p>Un modelo SVAR puede ser usado para identificar los shocks y trazar su función impulso respuesta o bien analizar su descomposición de varianza, lo anterior gracias a que podemos imponer ciertas restricciones en las matrices A y/o B.</p>
<p>Es de recalcar que si el modelo SVAR es un modelo estructural, parte de un modelo VAR(p) en su forma reducida:</p>
<p><span class="math display">\[\begin{equation}
Ax_t = A\Gamma x_{t−1} + Bw_t
\end{equation}\]</span></p>
<p>Donde solo se pueden agregar restricciones para A y B. Además los residuos en su forma reducida se puede recuperar de un modelo SVAR por <span class="math inline">\(\eta_t=A^{-1}Bw_t=Qw_t\)</span> y su matriz de varianza-covarianza es <span class="math inline">\(\Sigma_\eta=A^{-1}B\Sigma_{w}B^{\tau}(A^{-1})^{\tau}=Q\Sigma_{w}Q^{\tau}=QQ^{\tau}\)</span>.</p>
<p>De manera que el impulso respuesta de este modelo ante un shock estrutural en (<span class="math inline">\(w_t\)</span>) viene dado por:</p>
<p><span class="math inline">\(\begin{array}{ccccccccc} w_{t} &amp;\colon &amp;0&amp;0&amp;I&amp;0&amp;0&amp;0&amp;0 \\ x_{t} &amp;\colon &amp;0&amp;0&amp;A^{-1}B&amp;B&amp;AB&amp;A^{2}B&amp;\cdots \end{array}\)</span></p>
<p>Es posible distinguir tres tipos de SVAR según se impongan las restricciones:</p>
<ol style="list-style-type: decimal">
<li><p><em>Modelo A</em> La matriz B corresponde a <span class="math inline">\(I_{k}\)</span> lo que implica que el número mínimo de restricciones para su identificación es <span class="math inline">\(k\frac{(k-1)}{2}\)</span></p></li>
<li><p><em>Modelo B</em> La matriz A corresponde a <span class="math inline">\(I_{k}\)</span> lo que implica que el número mínimo de restricciones para su identificación es <span class="math inline">\(k\frac{(k-1)}{2}\)</span></p></li>
<li><p><em>Modelo AB</em> Las restricciones pueden ser impuestas en ambas matrices siendo el número mínimo de restricciones para su identificación es <span class="math inline">\(k^{2}+k\frac{(k-1)}{2}\)</span></p></li>
</ol>
</div>
<div id="ortogonalización" class="section level2" number="1.4">
<h2><span class="header-section-number">1.4</span> Ortogonalización</h2>
<p>La función impulso respuesta de un VAR es ligeramente ambigua.</p>
<p>Sabemos que podemos representar cualquier serie de tiempo como una <em>arbitraria</em> combinación lineal de un conjunto de funciones de impulso respuestas.</p>
<p>Entonces la <em>Ortogonalización</em> se refiere al proceso de seleccionar uno de las posibles funciones de impulsos respuestas que sea más interesante para el análisis económico.</p>
<p>Si definimos la matriz <span class="math inline">\(A^{*}\)</span> en función del operador de rezagos:
<span class="math display">\[\begin{equation}
A^{*}=\left( \begin{array}{cccc}
L      &amp; NA  &amp; \cdots &amp; NA\\
\beta_{1,2} &amp; L   &amp;        &amp; NA\\
\vdots &amp;     &amp; \ddots &amp; NA\\
\beta_{1,k} &amp; \beta_{2,k}   &amp; \cdots &amp; L\\
\end{array}
\right)
\end{equation}\]</span></p>
<p>Un VAR expresado en notación vectorial estaría dado:</p>
<p><span class="math display">\[\begin{align}
A^{*}(L)x_{t}&amp;=w_{t},\;\;A^{*}(0)=I,\;\;E(w_{t}w_{t}^{&#39;})=\Sigma_w 
\end{align}\]</span></p>
<p>Si definimos la matriz B en función de sus rezagos:
<span class="math display">\[\begin{equation}
B^{*}=\left( \begin{array}{cccc}
L      &amp; NA  &amp; \cdots &amp; NA\\
\Phi_{1,2} &amp; L   &amp;        &amp; NA\\
\vdots &amp;     &amp; \ddots &amp; NA\\
\Phi_{1,k} &amp; \Phi_{2,k}   &amp; \cdots &amp; L\\
\end{array}
\right)
\end{equation}\]</span></p>
<p>En notación MA se escribe:</p>
<p><span class="math display">\[\begin{align}
x_{t}&amp;=B^{*}(L)w_{t},\;\;B^{*}(0)=I,\;\;E(w_{t}w_{t}^{&#39;})=\Sigma_w 
\end{align}\]</span></p>
<p>Donde <span class="math inline">\(B^{*}(L)=A^{*}(L)^{-1}\)</span>, siendo <span class="math inline">\(B^{*}(L)\)</span> la respuesta de <span class="math inline">\(x_{t}\)</span> a una unidad de impulso de cada elemento de <span class="math inline">\(e_{t}\)</span></p>
<p>Ahora supongase que queremos calcular la respuesta de <span class="math inline">\(x_{t}\)</span> a un nuevo shock, el cual es una combinación lineal de viejos schocks, por ejemplo usted quiere calcular el efecto de <span class="math inline">\(x_{t}\)</span> de un schocks tal que: <span class="math inline">\(\eta_{1t}=e_{\pi t}\)</span> y <span class="math inline">\(\eta_{2t}=5e_{\pi t}+e_{mt}\)</span> ó:
<span class="math display">\[\begin{equation}
\eta_{t}=Qw_t,\;\;Q=\left( \begin{array}{cc}
    1 &amp; 0\\
    5 &amp; 1
\end{array}
\right) \nonumber
\end{equation}\]</span></p>
<p>Con ello podemos reescribir el VAR en notación MA:
<span class="math display">\[\begin{align}
x_{t}&amp;=C(L)\eta_{t},\;\;C(L)=B^{*}(L)Q^{-1}
\end{align}\]</span></p>
<p>Donde C(L) representa la respuesta de <span class="math inline">\(x_{t}\)</span> a los schocks <span class="math inline">\(\eta_{t}\)</span>, ó visto de una forma alternativa C(L) sería una combinación lineal de los impulsos respuestas originales <span class="math inline">\(B^{*}(L)\)</span>.</p>
<p>Pero ¿Qué combinación lineal deberíamos observar?</p>
<p>Es de notar que los datos no nos pueden ayudar ya que tanto la representación <span class="math inline">\(x_{t}=B^{*}(L)w_{t}\)</span> y <span class="math inline">\(x_{t}=C(L)\eta_{t}\)</span> son equivalentes y producen las mismas series.</p>
<p>Así que somos nosotros quienes decidimos cual combinación lineal es más interesante, en base a un conjunto de supuestos llamados <em>supuestos de ortogonalización</em>.</p>
</div>
<div id="supuestos-de-ortogonalización" class="section level2" number="1.5">
<h2><span class="header-section-number">1.5</span> Supuestos de Ortogonalización</h2>
<p>El primero y quizás el más popular supuesto es que los shocks son ortogonales (no están correlacionados).</p>
<p>Si dos shocks <span class="math inline">\(e_{\pi t}\)</span> y <span class="math inline">\(e_{mt}\)</span> están correlacionados entonces no tiene sentido preguntarse, ¿qué pasa si <span class="math inline">\(e_{\pi t}\)</span> se impulsa en una unidad?, pues obviamente también se estaría moviendo <span class="math inline">\(e_{mt}\)</span> al mismo tiempo.</p>
<p>Un ejemplo concreto, nosotros queremos saber la función impulso respuesta en términos causales, es decir el <em>efecto</em> de la inflación en el precio de las manzanas. Pero si el shock de la inflación está correlacionado al shock del precio de las manzanas, no podemos saber si lo que estamos viendo como respuesta del precio de las manzanas se debe a un shock de inflación ó es debido a un shock en la oferta de las manzanas.</p>
<p>Adicionalmente es conveniente reescalar el shock para que este se exprese en unidades de la varianza de las series.</p>
<p>El supuesto de shocks ortogonales busca encontrar una matriz Q, tal que <span class="math inline">\(E(\eta_{t}\eta_{t}^{&#39;})=I\)</span>. Por lo cual:</p>
<p><span class="math display">\[\begin{align}
Q^{-1}Q^{-1&#39;}&amp;=\Sigma_{\eta} \\
E(\eta_{t}\eta_{t}^{&#39;})&amp;=E(Qw_{t}w_{t}^{&#39;}Q^{&#39;})=Q\Sigma_{w} Q^{&#39;}=I\nonumber
\end{align}\]</span></p>
</div>
<div id="ortogonalización-de-sims" class="section level2" number="1.6">
<h2><span class="header-section-number">1.6</span> Ortogonalización de Sims</h2>
<p>Una vía de construir la matriz Q es por la descomposición de Choleski.</p>
<p>Desafortunadamente existen muchas matrices Q que pueden hacer cumplir la identidad <span class="math inline">\(E(\eta_{t}\eta_{t}^{&#39;})=I\)</span>, entonces la pregunta es: ¿cuál de esas matrices Q hay que escoger?: La respuesta dependerá de las propiedades que impongamos del proceso MA ó C(L), en concreto se utilizara la teoría económica para especificar C(0) y C(1).</p>
<p>Sims sugiere que se especifica las propiedades de C(0).</p>
<p>Enfatizando el hecho de que sólo en el caso en que <span class="math inline">\(\Sigma_{w}\)</span> sea diagonal, cualquier diagonalización de la matriz Q debería tener elementos en la posición no diagonal y por tanto <span class="math inline">\(C(0)\neq I\)</span>, implicando que algún shocks debería tener efecto contemporáneo en más de una variable.</p>
<p>En especifico Sims sugiere escoger una matriz triangular inferior C(0) tal que:</p>
<p><span class="math display">\[\begin{equation}
    \left( \begin{array}{c}
    \pi_{t} \\
      m_{t} 
    \end{array}\right)=\left( \begin{array}{cc}
    C_{0\pi \pi} &amp; 0\\
    C_{0m  \pi} &amp; C_{0mm}
    \end{array}
    \right) \left( \begin{array}{c}
    \eta_{1t}\\
    \eta_{2t}
    \end{array}
    \right) +C_{1}\eta_{t-1}+\cdots
\end{equation}\]</span></p>
<p>La matriz triangular inferior C(0) implica que <span class="math inline">\(\pi_{t}\)</span> aparece en la ecuación de <span class="math inline">\(m_{t}\)</span>, pero <span class="math inline">\(m_{t}\)</span> no en la ecuación de <span class="math inline">\(\pi_{t}\)</span>. Para observar lo anterior podemos representar el sistema dado por la ecuación anterior como un proceso autorregresivo y ortogonalizado: <span class="math inline">\(D(L)x_{t}=\eta_{t}\)</span>, donde <span class="math inline">\(D(L)=C(L)^{-1}\)</span>; recordando que la inversa de una matriz triangular inferior es también una matriz triangular inferior, tenemos:</p>
<p><span class="math display">\[\begin{equation}
      \left( \begin{array}{cc}
      D_{0\pi m} &amp; 0\\
      D_{0m \pi} &amp; D_{0mm}
      \end{array}
      \right)
      \left( \begin{array}{c}
      \pi_{t} \\
       m_{t} 
      \end{array}\right)+D_{1}x_{t-1}+\cdots=\eta_{t}\nonumber
\end{equation}\]</span></p>
<p>Es de notar que la sugerencia de Sims es equivalente a estimar un sistema <span class="math inline">\((\pi_{t}, m_{t})\)</span> por OLS, en que la ecuación de <span class="math inline">\(m_{t}\)</span> tenga como regresor <span class="math inline">\(\pi_{t}\)</span>, pero no viceversa y escalando cada ecuación para que la varianza del error sea 1.</p>
<p><span class="math display">\[\begin{align}
\pi_{t}&amp;=\;\;\;\;\;\;\;\;\;\;\;\;\;\;\alpha_{1\pi \pi}\pi_{t-1}+\cdots+\alpha_{1\pi m}m_{t-1}+\cdots+\eta_{1t}\nonumber \\
m_{t}&amp;=\alpha_{0m \pi}\pi_{t}+\alpha_{1m \pi}\pi_{t-1}+\cdots+\alpha_{1mm}m_{t-1}+\cdots +\eta_{2t}\nonumber
\end{align}\]</span></p>
<p>En resumen se puede unicamente especificar la matriz Q como una combinación lineal de los shocks originales <span class="math inline">\((w_{t})\)</span> y elaborar los impulsos respuesta de acuerdo a:</p>
<ol style="list-style-type: decimal">
<li>El error <span class="math inline">\((w_{t})\)</span> son ortogonales.</li>
<li>Que la respuesta instantánea de una variable a un shock es cero, siendo este al caso de estimar un VAR por OLS con efecto contemporaneo de <span class="math inline">\(\pi\)</span> sobre m y no viceversa.</li>
</ol>
<p>Es de notar que si se específica C(0) se garantiza que al aplicar la descomposición de Choleski se produce una única matriz triangular inferior Q:
<span class="math display">\[\begin{align}
C(0)&amp;=B^{*}(0)Q^{-1}=A^{-1}BQ^{-1}=A^{-1}BQ \nonumber\\
\end{align}\]</span></p>
<p>Entonces lo importante es decidir el orden de prelación <em>De lo exógeno a lo endógeno</em> de las variables en el VAR; auxiliándose de la teoría económica.</p>
</div>
<div id="paquete-en-r" class="section level2" number="1.7">
<h2><span class="header-section-number">1.7</span> Paquete en R</h2>
<p>En esta nota para la obtención de un Vector Autorregresivo Estructural (SVAR) se utilizará el paquete en R <em>SVARS</em> elaborado por <span class="citation"><a href="#ref-SVAR21" role="doc-biblioref">Lange et al.</a> (<a href="#ref-SVAR21" role="doc-biblioref">2021</a>)</span>. A continuación se muestra la carga de este paquete junto a otros que serán de utilidad cuando se analicen los resultados.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(&quot;svars&quot;)</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;svars&quot;</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;ggplot2&quot;</span>)</span></code></pre></div>
<p>Enseguida se cargará una base de datos en frecuencia trimestral que contiene la brecha producto, la inflación de trimestre a trimestre del deflactor del PIB y una tasa de interés nominal del fondo federal.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;USA&quot;</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>usa<span class="ot">&lt;-</span><span class="fu">as.zoo</span>(USA)</span></code></pre></div>
<p>A continuación se replicará los resultados obtenidos por <span class="citation"><a href="#ref-Herwartz2016" role="doc-biblioref">Herwartz and Plödt</a> (<a href="#ref-Herwartz2016" role="doc-biblioref">2016</a>)</span>, específicamente se estimaran los shocks estructurales a través de la metodología de cambios en volatilidades. Ello se logra a través de la función <em>id.cv()</em> dentro del cual hay que indicarle la fecha a partir de la cual se dio ese cambio estructural.</p>
<p><span class="citation"><a href="#ref-Herwartz2016" role="doc-biblioref">Herwartz and Plödt</a> (<a href="#ref-Herwartz2016" role="doc-biblioref">2016</a>)</span> argumentan que el punto de quiebra se dio en el tercer trimestre de 1979 donde aconteció un cambio en la política de la Reserva Federal que redujo la volatilidad de las variables macroeconómicas (ver <span class="citation"><a href="#ref-Stock2003" role="doc-biblioref">Stock and Watson</a> (<a href="#ref-Stock2003" role="doc-biblioref">2003</a>)</span>)</p>
<p>Lo anterior es posible visualizarlo.
Un primer paso es visualizar cada una de las series.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(usa, <span class="at">facets =</span> T) <span class="sc">+</span> <span class="fu">theme_bw</span>() <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&#39;Evolución de series de USA&#39;</span>)</span></code></pre></div>
<p><img src="01-conceptos_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>Seguidamente se estimara la forma reducida de un VAR, aplicaremos una especificación que incluya intercepto y hasta seis rezagos (p=6)</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>plain.var <span class="ot">&lt;-</span> vars<span class="sc">::</span><span class="fu">VAR</span>(USA, <span class="at">p =</span> <span class="dv">6</span>, <span class="at">type =</span> <span class="st">&#39;const&#39;</span>)</span></code></pre></div>
<p>Con base en el objeto VAR podemos estimar su forma estructural con la función <em>id.cv()</em> la cual introduce el <em>cambio en la varianza</em> que se observa en las series, sin embargo la aplicación de esta función requiere específicar el argumento <em>SB</em> en formato <em>ts</em>:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>usa.cv <span class="ot">&lt;-</span> <span class="fu">id.cv</span>(plain.var, <span class="at">SB =</span> <span class="fu">c</span>(<span class="dv">1979</span>, <span class="dv">3</span>))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(usa.cv)</span></code></pre></div>
<pre><code>## 
## Identification Results
## ---------------------- 
## 
## Method: Changes in Volatility
## Sample size: 169
## Log-Likelihood: -564.2994
## AIC: 1268.599
## Structural Break: At Observation Number 59 during 1979 Q3
## Number of GLS estimations: 22
## Number of Restrictions: 0
## 
## Estimated unconditional Heteroscedasticity Matrix (Lambda):
##         [,1]     [,2]     [,3]
## x  0.3925906 0.000000 0.000000
## pi 0.0000000 0.191641 0.000000
## i  0.0000000 0.000000 1.244348
## 
## Standard Errors of Lambda:
##         [,1]       [,2]      [,3]
## x  0.0926582 0.00000000 0.0000000
## pi 0.0000000 0.04527264 0.0000000
## i  0.0000000 0.00000000 0.2935572
## 
## Estimated B Matrix (unique decomposition of the covariance matrix): 
##           [,1]       [,2]      [,3]
## x   0.61193300 -0.5931964 0.2241237
## pi  0.75559400  1.2987520 0.1131134
## i  -0.02899916  0.1572953 0.7084709
## 
## Standard Errors of B:
##         [,1]      [,2]       [,3]
## x  0.1330924 0.1955350 0.07101215
## pi 0.2498465 0.2600375 0.09960246
## i  0.1559672 0.1213446 0.07004431
## 
## Identification Wald Test of equal Eigenvalues:
## [1] 1.2443485 0.3925906 0.1916410
##                              Test statistic dof p-value  
## lambda_ 1 =lambda_2                  5.3828   2 0.06779 .
## lambda_ 1 =lambda_2=lambda_3        15.0586   5 0.01011 *
## lambda_ 2 =lambda_3                  2.1465   2 0.34189  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Si el VAR puede ser escrito con matrices y como un sistema de media móviles (como se verá más adelante) de la siguiente forma:</p>
<p><span class="math display">\[\begin{align}
x_{t}&amp;=B(L)\epsilon_{t},\;\;B(0)=I,\;\;E(\epsilon_{t}\epsilon_{t}^{&#39;})=\Sigma 
\end{align}\]</span><br />
Los resultados muestran la matriz de covarianza estimada <span class="math inline">\(\hat{B}\)</span>, la matriz de cambio en la convarianza estiamda <span class="math inline">\(\hat{\lambda}\)</span>.</p>
<p>Es de notar que el orden de las columnas en <span class="math inline">\(\hat{B}\)</span> es arbitrario. Lo importante es que ese ordenamiento se haga teniendo un sentido económico.</p>
<p>A pesar de lo anterior, <span class="citation"><a href="#ref-Herwartz2016" role="doc-biblioref">Herwartz and Plödt</a> (<a href="#ref-Herwartz2016" role="doc-biblioref">2016</a>)</span> hacen un ordenamiento de acuerdo con el patrón de signo único que indica la dirección de los choques. El siguiente código ordena las columnas de esa misma manera.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>usa.cv<span class="sc">$</span>B <span class="ot">&lt;-</span> usa.cv<span class="sc">$</span>B[, <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">1</span>)]</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>usa.cv<span class="sc">$</span>B[,<span class="dv">3</span>] <span class="ot">&lt;-</span> usa.cv<span class="sc">$</span>B[, <span class="dv">3</span>] <span class="sc">*</span> (<span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>usa.cv<span class="sc">$</span>B_SE <span class="ot">&lt;-</span> usa.cv<span class="sc">$</span>B_SE[, <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">1</span>)]</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>usa.cv<span class="sc">$</span>Lambda <span class="ot">&lt;-</span> <span class="fu">diag</span>(<span class="fu">diag</span>(usa.cv<span class="sc">$</span>Lambda)[<span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">1</span>)])</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>usa.cv<span class="sc">$</span>Lambda_SE <span class="ot">&lt;-</span> <span class="fu">diag</span>(<span class="fu">diag</span>(usa.cv<span class="sc">$</span>Lambda_SE)[<span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">1</span>)])</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(usa.cv<span class="sc">$</span>B, <span class="dv">3</span>)</span></code></pre></div>
<pre><code>##     [,1]   [,2]   [,3]
## x  0.224 -0.593 -0.612
## pi 0.113  1.299 -0.756
## i  0.708  0.157  0.029</code></pre>
<p><span class="citation"><a href="#ref-Herwartz2016" role="doc-biblioref">Herwartz and Plödt</a> (<a href="#ref-Herwartz2016" role="doc-biblioref">2016</a>)</span> interpretan el efecto de la primera columna de la matriz <span class="math inline">\(\hat{B}\)</span> como un shock de demanda. La segunda y tercera columna representan, respectivamente, un shock de oferta y política monetaria.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(usa.cv<span class="sc">$</span>Lambda, <span class="dv">3</span>)</span></code></pre></div>
<pre><code>##       [,1]  [,2]  [,3]
## [1,] 1.244 0.000 0.000
## [2,] 0.000 0.192 0.000
## [3,] 0.000 0.000 0.393</code></pre>
<p>En cambio la matriz <span class="math inline">\(\hat{\lambda}\)</span> representa la varianza de los shocks estructurales en un segundo regimén, esto es posterior al quiebre estructural. Los autores interpretan a partir de la diagonal de <span class="math inline">\(\hat{\lambda}\)</span> que los shocks de oferta y política monetaria tiene baja varianza en comparación a los shocks de demanda.</p>
<p>Los autores comparan estos resultados con los obtenidos por <span class="citation"><a href="#ref-Sims80" role="doc-biblioref">Sims</a> (<a href="#ref-Sims80" role="doc-biblioref">1980</a>)</span> utilizando la descomposición de la matriz de covarianza (<span class="math inline">\(\hat{B}\)</span>) como una matriz triangular inferior. La función <em>id.cv()</em> permite
probar tales restricciones configurando para ello una matriz triangular inferior como se describe en el código siguiente.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>restMat <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">9</span>), <span class="at">ncol =</span> <span class="dv">3</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>restMat[<span class="dv">1</span>, <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>)] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>restMat[<span class="dv">2</span>, <span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>restMat</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]   NA    0    0
## [2,]   NA   NA    0
## [3,]   NA   NA   NA</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>restricted.model <span class="ot">&lt;-</span> <span class="fu">id.cv</span>(plain.var, <span class="at">SB =</span> <span class="fu">c</span>(<span class="dv">1979</span>, <span class="dv">3</span>),<span class="at">restriction_matrix =</span> restMat)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(restricted.model)</span></code></pre></div>
<pre><code>## 
## Identification Results
## ---------------------- 
## 
## Method: Changes in Volatility
## Sample size: 169
## Log-Likelihood: -568.6664
## AIC: 1277.333
## Structural Break: At Observation Number 59 during 1979 Q3
## Number of GLS estimations: 23
## Number of Restrictions: 3
## 
## Estimated unconditional Heteroscedasticity Matrix (Lambda):
##         [,1]      [,2]      [,3]
## x  0.3501948 0.0000000 0.0000000
## pi 0.0000000 0.2346854 0.0000000
## i  0.0000000 0.0000000 0.9420116
## 
## Standard Errors of Lambda:
##          [,1]       [,2]     [,3]
## x  0.08266738 0.00000000 0.000000
## pi 0.00000000 0.05616318 0.000000
## i  0.00000000 0.00000000 0.227189
## 
## Estimated B Matrix (unique decomposition of the covariance matrix): 
##          [,1]      [,2]      [,3]
## x  0.87988465 0.0000000 0.0000000
## pi 0.08137972 1.5306503 0.0000000
## i  0.31518384 0.2606745 0.7378484
## 
## Standard Errors of B:
##          [,1]       [,2]       [,3]
## x  0.08638851 0.00000000 0.00000000
## pi 0.10334026 0.15169565 0.00000000
## i  0.08527441 0.08620187 0.07354585
## 
## Identification Wald Test of equal Eigenvalues:
## [1] 0.9420116 0.3501948 0.2346854
##                              Test statistic dof p-value
## lambda_ 1 =lambda_2                 4.04784   2  0.1321
## lambda_ 1 =lambda_2=lambda_3        9.15413   5  0.1031
## lambda_ 2 =lambda_3                 0.68408   2  0.7103
## 
## Likelihood Ratio Test: 
##  Test statistic p-value  
##           8.734   0.033 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Si partimos que los shocks structurales fueron identificados con la metodología de cambio en la matriz de covarianza, cualquier restricción impuesta sobre <span class="math inline">\(B\)</span> hace que el modelo esté sobre identificado y ello es posible probarse.</p>
<p>En resumen el “likelihood ratio test” indica que bajo la <span class="math inline">\(H_{0}\)</span>
que <span class="math inline">\(B\)</span> la matriz triangular (baja la cual impactan los shocks structurales) es rechazada al <span class="math inline">\(5\%\)</span> de nivel de significancia. <span class="citation"><a href="#ref-Herwartz2016" role="doc-biblioref">Herwartz and Plödt</a> (<a href="#ref-Herwartz2016" role="doc-biblioref">2016</a>)</span> argumentan que la identificación de valores iguales a cero para lograr una matriz trinagular inferior es algo contra intuitivo desde el punto de vista económico; por tanto un modelo sin restricciones debería ser preferido.</p>
<p>El siguiente paso es calcular la función impulso respuesta (IFR) con un intervalo de confianza obtenido a partir del método “boostrap.” A partir de la IFR es posible investigar los efectos futuros de los shocks estructurales etiquetados como “económicos” sobre las variables
incluidas en el modelo. De hecho de acuerdo a <span class="citation"><a href="#ref-Herwartz18" role="doc-biblioref">Herwartz</a> (<a href="#ref-Herwartz18" role="doc-biblioref">2018</a>)</span> aplicar la metodología "boostrap permite evaluar la significancia en los signos que se hacen patentes en la matriz <span class="math inline">\(\hat{B}\)</span>.</p>
<p>Para aplicar lo anterior, definimos una lista con los signos que representan nuestras restricciones tanto para los shocks de demanda, oferta y política monetaria.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>signrest <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">demand =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>), <span class="at">supply =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>), <span class="at">monetary_policy =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div>
<p>Notal que el horizonte de tiempo para el IFR tiene que ser determinado de antemano usando el argumento n.ahead.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>cores <span class="ot">&lt;-</span> parallel<span class="sc">::</span><span class="fu">detectCores</span>() <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">231</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>usa.cv.boot <span class="ot">&lt;-</span> <span class="fu">wild.boot</span>(usa.cv, <span class="at">design =</span> <span class="st">&quot;fixed&quot;</span>,<span class="at">distr =</span> <span class="st">&quot;rademacher&quot;</span>, <span class="at">nboot =</span> <span class="dv">1000</span>, <span class="at">n.ahead =</span> <span class="dv">15</span>,<span class="at">nc =</span> cores, <span class="at">signrest =</span> signrest)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(usa.cv.boot)</span></code></pre></div>
<pre><code>## 
## Bootstrap Results
## ----------------- 
## 
## Method: Wild bootstrap
## Bootstrap iterations: 1000
## Distribution used: rademacher
## Design: fixed
## 
## Point estimates: 
##         [,1]       [,2]        [,3]
## x  0.2241237 -0.5931964 -0.61193300
## pi 0.1131134  1.2987520 -0.75559400
## i  0.7084709  0.1572953  0.02899916
## 
## Bootstrap means: 
##          [,1]       [,2]       [,3]
## x  0.09580740 -0.5030485 -0.6303868
## pi 0.09639712  1.1310905 -0.7720157
## i  0.70100321  0.0364798 -0.1675659
## 
## Bootstrap standard errors: 
##          [,1]      [,2]      [,3]
## x  0.14143383 0.3077349 0.2494872
## pi 0.17500155 0.4556690 0.5925734
## i  0.07511879 0.2273595 0.2178134
## 
## Identified sign patterns: 
## =========================
## Specified sign pattern: 
## 
##    demand supply monetary_policy
## x       1     -1              -1
## pi      1      1              -1
## i       1      1               1
## 
## Unique occurrence of single shocks according to sign pattern: 
## demand : 65.5 % 
## supply : 66 % 
## monetary_policy : 28.4 % 
## 
## Joint occurrence of specified shocks: 12.7 %</code></pre>
<p>Enseguida, graficamos para cada variable y shocks su IFR.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(usa.cv.boot, <span class="at">lowerq =</span> <span class="fl">0.16</span>, <span class="at">upperq =</span> <span class="fl">0.84</span>)</span></code></pre></div>
<p><img src="01-conceptos_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>En resumen solamente el 12.7% de todos los bootstrap estimados están en línea con el patron de signos económicamente sensatos.
El signo del patron de shocks monetario esperado aparece en un 28.4%. Finalmente, el bootstrap muestra que el tercer shock va más en línea con el patrón asociado a un shock de demanda.</p>
</div>
<div id="bla-bla" class="section level2" number="1.8">
<h2><span class="header-section-number">1.8</span> BLA Bla</h2>
<p>La estructura del modelo determina el orden de prelación de cada una de las variables y las restricciones de corto plazo.
El vector está dado por X=[y, <span class="math inline">\(\pi\)</span>, i, NPL, L, e] y se establece un SVAR de la forma <span class="math inline">\(AX=X_{-1}+u\)</span>, en el que A contiene las restricciones y con el cual se identifica los shocks.
Los datos utilizados tienen la siguiente características:}</p>
<p><span class="math display">\[\begin{eqnarray}
AX&amp;=\begin{bmatrix}
1 &amp; 0 &amp; 1 &amp; 0 &amp; 0 &amp; 0  \\
1 &amp; 1 &amp; 0 &amp; 0 &amp; 0 &amp; 0 \\
0 &amp; 1 &amp; 1 &amp; 1 &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; 0 &amp; 1 &amp; 0 &amp; 0 \\
1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 &amp; 0 \\
1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 \end{bmatrix}
\begin{bmatrix}
y \\
\pi \\
i\\
NPL\\
L\\
e\end{bmatrix}
\end{eqnarray}\]</span></p>

</div>
</div>
<div id="referencias" class="section level1 unnumbered">
<h1>Referencias</h1>

<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-Herwartz18" class="csl-entry">
Herwartz, Helmut. 2018. <span>“<span class="nocase">Hodges–Lehmann Detection of Structural Shocks – An Analysis of Macroeconomic Dynamics in the Euro Area</span>.”</span> <em>Oxford Bulletin of Economics and Statistics</em> 80 (4): 736–54. <a href="https://doi.org/10.1111/obes.12234">https://doi.org/10.1111/obes.12234</a>.
</div>
<div id="ref-Herwartz2016" class="csl-entry">
Herwartz, Helmut, and Martin Plödt. 2016. <span>“<span class="nocase">Simulation Evidence on Theory-based and Statistical Identification under Volatility Breaks</span>.”</span> <em>Oxford Bulletin of Economics and Statistics</em> 78 (1): 94–112. <a href="https://ideas.repec.org/a/bla/obuest/v78y2016i1p94-112.html">https://ideas.repec.org/a/bla/obuest/v78y2016i1p94-112.html</a>.
</div>
<div id="ref-SVAR21" class="csl-entry">
Lange, Alexander, Bernhard Dalheimer, Helmut Herwartz, and Simone Maxand. 2021. <span>“Svars: An r Package for Data-Driven Identification in Multivariate Time Series Analysis.”</span> <em>Journal of Statistical Software</em> 97 (5): 1–34. <a href="https://doi.org/10.18637/jss.v097.i05">https://doi.org/10.18637/jss.v097.i05</a>.
</div>
<div id="ref-Sims80" class="csl-entry">
Sims, Christopher A. 1980. <span>“<span class="nocase">Macroeconomics and Reality</span>.”</span> <em>Econometrica</em> 48 (1): 1–48. <a href="https://ideas.repec.org/a/ecm/emetrp/v48y1980i1p1-48.html">https://ideas.repec.org/a/ecm/emetrp/v48y1980i1p1-48.html</a>.
</div>
<div id="ref-Stock2003" class="csl-entry">
Stock, James H., and Mark W. Watson. 2003. <span>“<span class="nocase">Has the Business Cycle Changed and Why?</span>”</span> In <em><span>NBER Macroeconomics Annual 2002, Volume 17</span></em>, 159–230. NBER Chapters. National Bureau of Economic Research, Inc. <a href="https://ideas.repec.org/h/nbr/nberch/11075.html">https://ideas.repec.org/h/nbr/nberch/11075.html</a>.
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>


    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["index.pdf", "index.epub"],
"toc": {
"collapse": "subsection",
"download": ["pdf", "epub"]
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
